### PR TITLE
Fix memory issue and update requirements

### PR DESCRIPTION
**Pull request by GuillaumeTh**
Fix fdata issue and update requirements.

Here the singularity built:
http://gofile.me/2HRRO/m3zFd2XAz

DON'T MERGE BEFORE TRACTOFLOW TO UPDATE THE VERSION INSIDE THE CONTAINERS.

### CODE REVIEW

**Comment by GuillaumeTh** [comment]
@arnaudbore I updated the readme too.

**Comment by GuillaumeTh** [comment]
@arnaudbore here the new link of the singularity: http://gofile.me/2HRRO/YPVwzNeiE

**Comment by GuillaumeTh** [comment]
Everythong is good to me. @arnaudbore merge when you want

**Comment by GuillaumeTh** [comment]
@arnaudbore I tested TractoFlow with the latest commit and worked perfectly ! Same thing for ABS.

**Review by arnaudbore — APPROVED** [review]

**Pull request merged**
